# Generated by Django 4.0.2 on 2024-01-24 12:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('texecrmapp', '0001_initial'),
        ('texeclientapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('number', models.CharField(blank=True, max_length=250, null=True)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('profile', models.ImageField(blank=True, default='static\\images\\static_image\\icon.svg', null=True, upload_to='images/propic')),
                ('joindate', models.DateField(default=datetime.date(2024, 1, 24), null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='active', max_length=255, null=True)),
                ('addres', models.TextField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('otp', models.CharField(blank=True, max_length=250, null=True)),
                ('designation', models.CharField(blank=True, max_length=250, null=True)),
                ('complaint', models.CharField(blank=True, max_length=250, null=True)),
                ('orders', models.CharField(blank=True, max_length=250, null=True)),
                ('preformance', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='order_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 24, 17, 54, 32, 989355), null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.CharField(blank=True, max_length=255, null=True)),
                ('work_status', models.CharField(blank=True, max_length=255, null=True)),
                ('order_no', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='texeclientapp.orders')),
                ('order_crm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='texecrmapp.orders_crm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='texeworkapp.user_registration')),
            ],
        ),
    ]
