# Generated by Django 4.0.2 on 2024-01-09 06:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texeclientapp', '0002_alter_registration_joindate'),
        ('texecrmapp', '0002_alter_complaint_service_date_register_and_more'),
        ('texeworkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='joindate',
            field=models.DateField(default=datetime.date(2024, 1, 9), null=True),
        ),
        migrations.CreateModel(
            name='order_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 9, 12, 6, 52, 657569), null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('time_taken', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='texeclientapp.orders')),
                ('order_crm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='texecrmapp.orders_crm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='texeworkapp.user_registration')),
            ],
        ),
    ]
